name = "request-shadowing"
main = "src/worker.ts"
compatibility_date = "2023-08-14"
node_compat = true
logpush = false

workers_dev = false
routes = [
  { pattern = "bwatkins.dev/jaja/one*", zone_name = "bwatkins.dev" },
]

[placement]
mode = "smart"

[vars]
DB_USERNAME = ""
DB_HOST = ""
DB_PORT = "5432"
DB_NAME = "request_shadowing"
