name = "request-shadowing"
main = "src/worker.ts"
compatibility_date = "2023-08-14"
node_compat = true
logpush = false

workers_dev = false
routes = [
  { pattern = "bwatkins.dev/jaja/a*", zone_name = "bwatkins.dev" }
]

[placement]
mode = "smart"
