name = "request-mirroring-api"
main = "src/worker.ts"
compatibility_date = "2023-08-21"
node_compat = true

workers_dev = true
[placement]
mode = "smart"

[vars]
DB_USERNAME = "postgresroot"
DB_HOST = "development-request-mirroring.cluster-c4l307anqk2y.us-west-2.rds.amazonaws.com"
DB_PORT = "5432"
DB_NAME = "request_mirroring"